spring.application.name=admin-service
# Port
server.port=8082

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/doconnect_admin_db
spring.datasource.username=root
spring.datasource.password=Priyanka@1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT - must be same secret as user-service
jwt.secret=doconnect_super_secret_key_123456789_abcdefgh
jwt.expiration=86400000

# User service URL (for inter-service calls)
user.service.url=http://localhost:8081

# Route for admin approval endpoints
spring.cloud.gateway.routes[8].id=admin-approval
spring.cloud.gateway.routes[8].uri=lb://admin-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/admin/**